platform :ios, '8.0'

target '掌上云购' do

pod 'AFNetworking','~>3.0.0'
pod 'JSONKit-NoWarning','~>1.1'
pod 'MBProgressHUD', '~>0.9.1'
pod 'MJRefresh', '~>3.1.12'
pod 'MJExtension', '~> 3.0.13'

pod 'ShareSDK3', '~> 3.4.0'
pod 'MOBFoundation', '~> 2.0.8'
pod 'ShareSDK3/ShareSDKUI', '~> 3.4.0'
pod 'ShareSDK3/ShareSDKPlatforms/QQ', '~> 3.4.0'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo', '~> 3.4.0'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat', '~> 3.4.0'
pod 'SS-BaiduPushSDK', '~> 1.4.5'

end
